### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by clnsdzy** [gbolly11/recipe.com#1]
Kindly preview the minor fixes below and implement them on your project:

- [x] Cakes card issue - Use 3 rows to separate the 9 cards to fix the overflowing problem. So, each row will have only 3 cards.
- [x] Link all navigation elements (both desktop and sidenav) to each corresponding section.
- [x] Do the same task above for the footer navigation elements
- [x] Convert your name in the copyright section to a link that redirects to your GitHub profile.
- [x] Add a class of 'hoverable' to each card to give them a shadow element when hovered on.
`<div class="card...hoverable"></div>`
The parallax effect does not work on mobile devices. Use the M.css hide classes to: 
- [x] make the parallax component visible only on desktop devices
- [x] and a responsive image (of the same picture as the corresponding parallax) to show on tablets and smartphones

After implementing any of the changes above, click on the checkbox to indicate completion. When you're done completely, mark this Issue as done

**Comment by gbolly11** [comment]
Our name that redirects us to the GitHub profile has a default color set so I had to use class="white-text" on the <a> @collinsduzzy

**Comment by gbolly11** [comment]
Also to make the parallax visible on desktop I used the "hide-on-med-and-down" hope I'm correct @collinsduzzy

**Comment by gbolly11** [comment]
The last box is confusing Sir @collinsduzzy

**Comment by clnsdzy** [comment]
How confusing?

**Comment by clnsdzy** [comment]
> Also to make the parallax visible on desktop I used the "hide-on-med-and-down" hope I'm correct @collinsduzzy 

Correct 💯

**Comment by clnsdzy** [comment]
> Our name that redirects us to the GitHub profile has a default color set so I had to use class="white-text" on the @collinsduzzy

It's okay. Give it an underlined property when hovered on.

**Comment by gbolly11** [comment]
> > Our name that redirects us to the GitHub profile has a default color set so I had to use class="white-text" on the @collinsduzzy
> 
> It's okay. Give it an underlined property when hovered on.

@collinsduzzy the hover effect I couldn't do it but I'm done with everything.
